- CWE-312/README.md
- CWE-319/README.md
- CWE-327/CWE-327.py
- CWE-327/README.md
- CWE-327/useOfCryptographicAlgo.json
- CWE-532/README.md
- CWE-749/README.md
- CWE-780/CWE-780.py
- CWE-780/README.md
- CWE-798/README.md
- CWE-89/README.md
- CWE-921/README.md
- CWE-926/README.md
- CWE-94/README.md
This PR aims to update Quark Script to the repo and complete the README file of each Quark Script showcase.
+ Add CWE-327 Quark Script 
+ Add a README file to each showcase
> Add READMES to quark script showcases

- CWE-79/CWE-79.py
- CWE-79/README.md
- CWE-79/loadUrlFromIntent.json
This PR aims to close Issue #3 
+ Add CWE-79.py Quark Script
+ Add loadUrlFromIntent.json Rule file
+ Add README of CWE-79
> Add CWE-79 Quark-Script and README to the repo

- CWE-749/CWE-749.py
- CWE-749/README.md
This PR aims to closed issue #10 .
+ CWE-749/CWE-749.py
+ CWE-749/README.md
> Fix syntax error in the Quark Script for CWE-749

- CWE-489/CWE-489.py
- CWE-489/README.md
Add Quark Script for detecting CWE-489.  
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/458).
CWE-489/CWE-489.py  
CWE-489/README.md
> Add CWE-489 Quark Script

- CWE-22/CWE-22.py
- CWE-22/README.md
- CWE-22/accessFileInExternalDir.json
Add Quark Script for detecting CWE-22.  
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/460).
CWE-22/CWE-22.py  
CWE-22/README.md
CWE-22/accessFileInExternalDir.json
> Add CWE-22 Quark Script

- CWE-23/CWE-23.py
- CWE-23/README.md
- CWE-23/accessFileInExternalDir.json
Add Quark Script for detecting CWE-23.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/476).
CWE-23/CWE-23.py
CWE-23/README.md
CWE-23/accessFileInExternalDir.json
> Add CWE-23 Quark Script

- CWE-23/README.md
This PR aims to closed issue [#18](https://github.com/quark-engine/quark-script/issues/18) .
CWE-23/README.md
> Fix CWE-23 README.md format

- CWE-338/CWE-338.py
- CWE-338/README.md
- CWE-338/useMethodOfPRNG.json
Add Quark Script for detecting CWE-338.
Refer to this https://github.com/quark-engine/quark-engine/pull/475.
CWE-338/CWE-338.py
CWE-338/README.md
CWE-338/useMethodOfPRNG.json
> Add CWE-338 Quark Script

- CWE-295/CWE-295.py
- CWE-295/README.md
This PR aims to cthe Issue https://github.com/quark-engine/quark-script/issues/7
Add CWE-295.py Quark Script
Add README.md README
> [Quark-Script#7] Add CWE-295 Quark-Script and README to the repo

- CWE-88/CWE-88.py
- CWE-88/ExternalStringCommand.json
- CWE-88/README.md
Add Quark Script for detecting CWE-88.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/503).
CWE-88/CWE-88.py
CWE-88/README.md
CWE-88/ExternalStringCommand.json
> Add CWE-88 Quark Script

- CWE-925/CWE-925.py
- CWE-925/README.md
Add Quark Script for detecting CWE-925.
Refer to [this](https://github.com/quark-engine/quark-engine/pull/500)
CWE-925/CWE-925.py
CWE-925/README.md
> Add CWE-925 Quark Script

- .github/workflows/testQuarkScript.yml
> Install packages with pip instead of Setuptools in CI

- CWE-73/CWE-73.py
- CWE-73/README.md
- CWE-73/accessFileInExternalDir.json
Add Quark Script for detecting CWE-73.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/514)
CWE-73/CWE-73.py
CWE-73/README.md
CWE-73/accessFileInExternalDir.json
> Add CWE-73 Quark Script

- CWE-78/CWE-78.py
- CWE-78/ExternalStringCommand.json
- CWE-78/README.md
- CWE-88/CWE-88.py
- CWE-88/README.md
Add Quark Script for detecting CWE-78.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/519).
CWE-78/CWE-78.py
CWE-78/README.md
CWE-78/ExternalStringCommand.json
CWE-88/CWE-88.py
CWE-88/README.md
> Add CWE-78 and fix CWE-88 Quark Script

- CWE-940/CWE-940.py
- CWE-940/LoadUrlFromIntent.json
- CWE-940/README.md
Add Quark Script for detecting CWE-940.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/539).
CWE-940/CWE-940.py
CWE-940/README.md
CWE-940/LoadUrlFromIntent.json
> Add CWE-940 Quark Script

- CWE-780/README.md
Refer to [this issue](https://github.com/quark-engine/quark-engine/issues/564).
> Fix typo in quark script for CWE-780

- CWE-502/CWE-502.py
- CWE-502/README.md
- CWE-502/deserializeData.json
Add Quark Script for detecting CWE-502.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/572).
CWE-502/CWE-502.py
CWE-502/README.md
CWE-502/deserializeData.json
> Add CWE-502 Quark Script

- CWE-117/CWE-117.py
- CWE-117/README.md
- CWE-117/writeContentToLog.json
Add Quark Script for detecting CWE-117.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/535).
CWE-117/CWE-117.py
CWE-117/README.md
CWE-117/writeContentToLog.json
> Add CWE-117 Quark Script

- CWE-601/CWE-601.py
- CWE-601/README.md
Add Quark Script for detecting CWE-601.
Refer to this [PR](https://github.com/quark-engine/quark-engine/pull/591).
CWE-601/CWE-601.py
CWE-601/README.md
> Add CWE-601 Quark Script

- README.md
Description:
Correct the README by adding the missing tool description for Quark Script Agent.
Change File:
- README.md
> Fix Quark Script Agent Image in README

- CWE-329/CWE-329.py
- CWE-329/README.md
- CWE-329/initializeCipherWithIV.json
> Add CWE-329 Quark Script
